before_install:
    - sudo apt-get update -qq
install:
    - sudo apt-get install -qq coinor-libosi-dev python-dev libboost-python-dev
python:
    - 2.7
before_script:
    - sudo updatedb
    - locate osi.pc
    - locate python.pc
    - sudo pip install yaposib
script:
    - yaposib-config
