before_install:
    - sudo apt-get update -qq
install:
    - sudo apt-get install -qq build-essential
    - sudo apt-get install -qq pkg-config
    - sudo apt-get install -qq coinor-libosi-dev
    - sudo apt-get install -qq python-dev
    - sudo apt-get install -qq libboost-python-dev
python:
    - 2.7
env:
    - PKG_CONFIG_PATH=/usr/lib/`uname -m`-linux-gnu/pkgconfig/:${PKG_CONFIG_PATH}
before_script:
    -  sudo pip install yaposib
script:
    - yaposib-config
