before_install:
    - sudo apt-get update -qq
install:
    - sudo apt-get install -qq coinor-libosi-dev python-dev libboost-python-dev
python:
    - 2.7
env:
    - PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig/:${PKG_CONFIG_PATH}
before_script:
    - ls /usr/lib
    - uname -a
    -  sudo pip install yaposib
script:
    - yaposib-config
