language:
    - python
before_install:
    - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
    - sudo apt-get update -qq
install:
    - sudo apt-get install -qq build-essential pkg-config
    - sudo apt-get install -qq python-dev libboost-python-dev
    - sudo apt-get install -qq coinor-libosi-dev coinor-libcoinutils-dev coinor-libclp-dev libbz2-dev
python:
    - 2.7
before_script:
    - sudo python setup.py install
script:
    - sh scripts/yaposib-config
