before_install:
    - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
    - sudo apt-get update -qq
install:
    - sudo apt-get install -qq build-essential
    - sudo apt-get install -qq pkg-config
    - sudo apt-get install -qq coinor-libosi-dev
    - sudo apt-get install -qq coinor-libcoinutils-dev
    - sudo apt-get install -qq coinor-libclp-dev
    - sudo apt-get install -qq libbz2-dev
    - sudo apt-get install -qq python-dev
    - sudo apt-get install -qq libboost-python-dev
python:
    - 2.7
before_script:
    -  sudo python setup.py install
script:
    - yaposib-config
